services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Admin@123456"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - sdias-network

    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S 127.0.0.1 -U sa -P 'Admin@123456' -C -Q 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  api:
    container_name: rest-api
    build:
      context: .
      dockerfile: Dockerfile
    restart: always

    depends_on:
      sqlserver:
        condition: service_healthy

    environment:      
      ASPNETCORE_HTTP_PORTS: "8080"
      ASPNETCORE_ENVIRONMENT: Development

      TokenConfiguration__Secret: ${TOKEN_SECRET}
      TokenConfiguration__Issuer: "rest-api"
      TokenConfiguration__Audience: "rest-api"
      TokenConfiguration__ExpireMinutes: "60"

      ConnectionStrings__SqlServerConnection: ${SQLSERVER_CONNECTION}
    ports:
      - "8080:8080"

    networks:
      - sdias-network

    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:8080/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

volumes:
  sql_data:

networks:
  sdias-network:
    driver: bridge